name: deploy

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ kingtam.cf ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                submodules: true
                fetch-depth: 0

          - name: Setup Hugo
            uses: peaceiris/actions-hugo@v2
            with:
                hugo-version: '0.112.5'
                extended: true

          - name: Build Web
            run: hugo

          - name: Deploy Web
            uses: peaceiris/actions-gh-pages@v3
            with:
                PERSONAL_TOKEN: ${{ secrets.GH_PAGE_ACTION_TOKEN }}
                EXTERNAL_REPOSITORY: sillydanny/sillydanny.github.io
                PUBLISH_BRANCH: kingtam.cf
                PUBLISH_DIR: ./public
                commit_message: ${{ github.event.head_commit.message }}
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: public/
        remote_path: /apps/blog-kingtam-cf/html/
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
